ClientEvents.lang('zh_cn', event => {
  // 格式：event.renameItem('模组:物品ID', '新名字')
  event.renameItem('oceansdelight:tentacles', '碎鱿鱼须')
  event.renameItem('oceansdelight:stuffed_cod', '填馅鳕鱼')
  event.renameItem('oceansdelight:cooked_stuffed_cod', '烤填馅鳕鱼')
  event.renameItem('oceansdelight:honey_fried_kelp', '蜂蜜炸海带')
 /*event.renameItem('minersdelight:glow_squid', '小发光鱿鱼')
  event.renameItem('minersdelight:squid', '小鱿鱼')
  event.renameItem('minersdelight:baked_squid', '烤小鱿鱼')
  event.renameItem('minersdelight:tentacles', '小鱿鱼须')
  event.renameItem('minersdelight:baked_tentacles', '烤小鱿鱼须')*/
  event.renameItem('oceansdelight:seagrass_salad', '海草沙拉')
  event.renameItem('expandeddelight:apple_juice','鲜榨苹果汁')
  event.renameItem('createtransmission:transmission_chain', '传动链')
  event.renameItem('expandeddelight:sweet_berry_juice','鲜榨甜浆果汁') 
  event.renameItem('expandeddelight:glow_berry_juice','鲜榨发光浆果汁')
  event.renameItem('expandeddelight:cranberry_juice','鲜榨蔓越莓汁')
  event.renameItem('expandeddelight:sweet_berry_jelly','煮甜浆果酱') 
  event.renameItem('expandeddelight:glow_berry_jelly','煮发光浆果酱')
  event.renameItem('expandeddelight:cranberry_jelly','煮蔓越莓果酱')
  event.renameItem('expandeddelight:cranberry_jelly_sandwich','蔓越莓果酱三明治')
  event.renameItem('create_confectionery:marshmallow','史莱姆棉花糖')
  event.renameItem('create:dough','粗制面团')
  //event.renameItem('expandeddelight:salt','磨制岩盐')
  event.renameItem('expandeddelight:salt','精盐')
  event.renameItem('northstar:salt','粗盐')
  //event.renameItem('createfood:salt','精盐')
  event.renameItem('ccq_core:totem_unable','无魔力的不死图腾')
  event.renameItem('ccq_core:totem','未完成的不死图腾')
  event.renameItem('ccq_core:elytra','未完成的鞘翅')
  event.renameItem('ccq_core:elytra_unable','鞘翅模型')
  event.renameItem('ccq_core:heavy_core_u','未完成的沉重核心')
  //event.renameItem('create_confectionery:crushed_cocoa','神秘棕色粉末')
  event.renameItem('kaleidoscope_cookery:dumpling','煮饺子')
  event.renameItem('kaleidoscope_cookery:pork_bone_soup','纯骨大骨汤')
  event.renameItem('expandeddelight:mac_and_cheese','热芝士通心粉')
  event.renameItem('ccq_core:mineral_fish','矿物鱼')
  event.renameItem('createbigcannons:bronze_ingot','青铜锭')

  event.renameBlock('netherexp:wither_bone_block','凋灵化骨块')
  event.renameBlock('createbigcannons:bronze_block','青铜块')
  event.renameBlock('supplementaries:cog_block','红石传动块')
  event.renameBlock('supplementaries:enderman_head','末影人头监视器')
})

ClientEvents.lang('en_us', event => {
  event.renameItem('oceansdelight:tentacles', 'Chopped Squid Tentacles')
  event.renameItem('oceansdelight:stuffed_cod', 'Stuffed Cod')
  event.renameItem('oceansdelight:cooked_stuffed_cod', 'Cooked Stuffed Cod')
  event.renameItem('oceansdelight:honey_fried_kelp', 'Honey Fried Kelp')
 /* event.renameItem('minersdelight:glow_squid', 'Small Glow Squid')
  event.renameItem('minersdelight:squid', 'Small Squid')
  event.renameItem('minersdelight:baked_squid', 'Baked Small Squid')
  event.renameItem('minersdelight:tentacles', 'Small Squid Tentacles')
  event.renameItem('minersdelight:baked_tentacles', 'Baked Small Squid Tentacles')*/
  event.renameItem('oceansdelight:seagrass_salad', 'Seagrass Salad')
  event.renameItem('expandeddelight:apple_juice', 'Fresh Apple Juice')
  event.renameItem('createtransmission:transmission_chain', 'Transmission Chain')
  event.renameItem('expandeddelight:sweet_berry_juice', 'Fresh Sweet Berry Juice')
  event.renameItem('expandeddelight:glow_berry_juice', 'Fresh Glow Berry Juice')
  event.renameItem('expandeddelight:cranberry_juice', 'Fresh Cranberry Juice')
  event.renameItem('expandeddelight:sweet_berry_jelly', 'Cooked Sweet Berry Jelly')
  event.renameItem('expandeddelight:glow_berry_jelly', 'Cooked Glow Berry Jelly')
  event.renameItem('expandeddelight:cranberry_jelly', 'Cooked Cranberry Jelly')
  event.renameItem('expandeddelight:cranberry_jelly_sandwich', 'Cranberry Jelly Sandwich')
  event.renameItem('create_confectionery:marshmallow', 'Slime Marshmallow')
  event.renameItem('create:dough', 'Rough Dough')
  //event.renameItem('expandeddelight:salt','磨制岩盐')
  event.renameItem('expandeddelight:salt', 'Refined Salt')
  event.renameItem('northstar:salt', 'Coarse Salt')
  //event.renameItem('createfood:salt','精盐')
  event.renameItem('ccq_core:totem_unable', 'Magicless Totem of Undying')
  event.renameItem('ccq_core:totem', 'Unfinished Totem of Undying')
  event.renameItem('ccq_core:elytra', 'Unfinished Elytra')
  event.renameItem('ccq_core:elytra_unable', 'Elytra Model')
  event.renameItem('ccq_core:heavy_core_u', 'Unfinished Heavy Core')
  event.renameItem('create_confectionery:crushed_cocoa', 'Mysterious Brown Powder')
  event.renameItem('kaleidoscope_cookery:dumpling', 'Cooked Dumplings')
  event.renameItem('kaleidoscope_cookery:pork_bone_soup', 'Pure Bone Broth')
  event.renameItem('expandeddelight:mac_and_cheese', 'Hot Mac and Cheese')
  event.renameItem('ccq_core:mineral_fish', 'Mineral Fish')
  event.renameItem('createbigcannons:bronze_ingot', 'Bronze Ingot')

  event.renameBlock('netherexp:wither_bone_block', 'Withered Bone Block')
})