#If true, when shoot during aiming and has a scope installed,
#make tracer start under the scope, instead of from the center of the scope.
#
#Added in version 5.9.3
improve_tracer_start_position_when_aiming = true
#If true, hint users to install TaCZ Arcana for weapons that use its ammo type system.
hint_arcana_installation = true
#How to display the current ammo type's name.
#- DISABLE: Show TaCZ's version (vanilla behavior)
#- ENABLE:  Show the ammo type's name with original color
#- STYLED:  Show the ammo type's name with unified color
#
#Added in version 6.2.0
#Allowed Values: DISABLE, ENABLE, STYLED
hud_ammo_type_name_option = "STYLED"
#How to display the current ammo type's icon.
#- DISABLE: Don't display
#- ENABLE:  Show the ammo type's slot texture
#- STYLED:  Show the ammo type's slot texture with a shader that makes it more suitable with other parts of the gun HUD
#
#Warning: Incompatible with TaCZ Presence
#Added in version 6.2.0
#Allowed Values: DISABLE, ENABLE, STYLED
hud_ammo_type_icon_option = "STYLED"
#Max rangefinding distance for aiming target related papi
#
#Added in version 6.4.0
# Default: 128.0
# Range: 0.0 ~ 1024.0
papi_rangefinding_distance = 128.0
